apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: frontend
   labels: 
      app: guestbook
      tire: frontend

spec: 
   replicas: 2
   selector:
      matchLabels:
         tier: frontend

   template:
         metadata: 
            labels:
              tier: frontend

         spec: 
           containers:
           - name: php-redis
             image: gcr.io/google.sample/gb-frontend:v3

