# this pod impot cerdential from secret continer 

apiVersion: v1
kind: Pod
metadata: 
   name: secret-env-pod

spec:
   containers:
     - name: mycontainer
       iamge: redis
       env:
         - name: SECRET_USERNAME
           valueFrom:
              name: my-secret-cont
              key: username
              optional: false

         - name: SECRET_PASSWORD
           valueFrom: 
              secretKeyRef:
                 name: my-secret-cont
                 key: passwd
                 optional: false

restartPolicey: never
