# siple manifesto for creating pod of secret

apiVersion: v1
kind: Secret
metadata: 
   name: db-secret
type: opque
data: 
   mysql_root_passwd:           #pest decoded passwd ny base64





##    import credential  from running container


apiVersion: v1
kind: pod
metadata: 
   name: mycontainer

spec: 
   containers:
     - name: 
       image:
         envFrom:
           -secretRef:
              name: db-secrete     #pod name containing secret



##if i want to chose some spacific variable then


apiVersion: v1
kind: pod 
metadata: 
   name: mycontsecr

spec:
   containers:
      - name: 
        image:
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
               secretKeyRef:
                  name: db-secret
                  key: my_root_password

